---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Post
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content/pojects
  label: Project
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - project
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: src/
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
