---
label: Portfolio
hide_body: false
fields:
  - type: text
    name: name
    label: Name
    description: product description
  - type: textarea
    name: description
    label: Description
    description: product description
  - type: file
    name: image
    label: Image
    description: product image
  - name: price
    type: number
    label: Price
    description: item price
    default: 0
    required: true
    config:
      min:
      max:
      step:
